return {
	Swing = {
		ShowGizmos = false, -- Set to true to draw swinging trajectory lines
	},
	WallDetection = {
		ShowGizmos = false, -- Set to true to draw wall detection rays and hit points
	},
	WallRunProjection = {
		ShowGizmos = false, -- Set to true to draw wall run motion vector projections
	},
	MoveDirection = {
		ShowGizmos = false, -- Set to true to draw character movement direction vectors
	},
	DashBump = {
		ShowGizmos = true, -- Set to true to draw 3D Spherecast and swept collision volume gizmos
	},
}
